version: 0.2

env:
  variables:
    SONAR_URL: "http://54.173.154.249:9000"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Scanning Tools..."
      # Install Trivy
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.tar.gz
      - tar zxvf trivy_0.18.3_Linux-64bit.tar.gz
      # Install OWASP Dependency-Check
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
      - unzip dependency-check-7.1.1-release.zip

  pre_build:
    commands:
      - echo "Running Security Scans..."
      # 1. OWASP Scan
      - ./dependency-check/bin/dependency-check.sh --project "Swiggy" --scan . --format "HTML" || true
      # 2. Trivy Scan
      - ./trivy fs .

  build:
    commands:
      - echo "Building Docker Image..."
      - docker build -t swiggy-app:latest .

  post_build:
    commands:
      - echo "Automation Success! Build and Scans completed."
