version: 0.2

env:
  parameter-store:
    SONAR_URL: "/swiggy/sonar/url"
    SONAR_TOKEN: "/swiggy/sonar/token"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Scanning Tools..."
      # Install Sonar Scanner
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
      - ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
      # Install Trivy
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.tar.gz
      - tar zxvf trivy_0.18.3_Linux-64bit.tar.gz
      # Install OWASP Dependency-Check
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
      - unzip dependency-check-7.1.1-release.zip

  pre_build:
    commands:
      - echo "Running 3-Point Security Scan..."
      # 1. SonarQube Scan
      - sonar-scanner -Dsonar.projectKey=swiggy-project -Dsonar.sources=. -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN
      # 2. OWASP Scan
      - ./dependency-check/bin/dependency-check.sh --project "Swiggy" --scan . --format "HTML"
      # 3. Trivy Scan
      - ./trivy fs .

  build:
    commands:
      - echo "Building Docker Image..."
      - docker build -t swiggy-app:latest .

  post_build:
    commands:
      - echo "Automation Success! Ready for Review."
