version: 0.2

env:
  variables:
    SONAR_URL: "http://54.173.154.249:9000"
    SONAR_TOKEN: "squ_5a9d7c2cda5ea966c74b7ef85a84aeebb404045d" 

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Scanning Tools..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip sonar-scanner-cli-4.7.0.2747-linux.zip
      - mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
      - ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.tar.gz
      - tar zxvf trivy_0.18.3_Linux-64bit.tar.gz
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.1.1/dependency-check-7.1.1-release.zip
      - unzip dependency-check-7.1.1-release.zip

  pre_build:
    commands:
      - echo "Starting SonarQube scan..."
      - sonar-scanner -Dsonar.projectKey=swiggy-project -Dsonar.sources=. -Dsonar.host.url=$SONAR_URL -Dsonar.token=$SONAR_TOKEN
      
      - echo "Starting OWASP scan (with offline mode forced to prevent freezing)..."
      # Adding '--noupdate' prevents OWASP from trying to download the huge NVD database from the internet and freezing your container
      - ./dependency-check/bin/dependency-check.sh --project "Swiggy" --scan . --format "HTML" --noupdate || true
      
      - echo "Starting Trivy scan..."
      - ./trivy fs .

  build:
    commands:
      - echo "Building Docker Image..."
      - docker build -t swiggy-app:latest .

  post_build:
    commands:
      - echo "Build and Scans completed successfully."
      - printf '[{"name":"swiggy-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
