steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/swiggy-repo/swiggy-app:$SHORT_SHA', '.']

  # Step 2: Push the built image to GCP Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/swiggy-repo/swiggy-app:$SHORT_SHA']

  # Step 3: Deploy to the GKE Cluster
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - run
      - --filename=gcp-deployment.yaml
      - --location=us-central1-a
      - --cluster=swiggy-cluster
